import math
print()
print("CALCULAR EQUAÇÕES DE 2º GRAU USANDO A FÓRMULA DE BHASKARA")
print()
a=float(input("Digite o valor do 'A': "))
b=float(input("Digite o valor do 'B': "))
c=float(input("Digite o valor do 'C': "))
print()
delta=float(b**2 - 4*a*c)
raiz_delta=float(delta**(1/2))
x1=float(-b+raiz_delta/2*a)
x2=float(-b-raiz_delta/2*a)
print("O valor de X' e: %.2f" %(x1))
print("O valor de X'' e: %.2f" %(x2))
