print("CÁLCULO DE VELOCIDADE (FÍSICA)")
print()
print("Velocidade = km/h")
print("Aceleração = m/s")
print("Tempo = segundos")
print()
vo=int(input("Digite a velocidade inicial: "))
a=int(input("Digite a aceleração do corpo: "))
t=int(input("Digite o tempo decorrido: "))
vf= vo + a * t
print()
print("A velocidade do corpo é de %i km/h." %(vf))
