print("These scars long have yearned for your tender caress.")
print("To bind ou fortunes, damn what the stars own")
print("Rend my heart open, then your love profess.")
print("A winding, weaving fate to wich we both atone")
print()
print("You flee my dream come the morning.")
print("Your scent - berries tart, lilac sweet")
print("To dream of raven locks entwisted, stormy.")
print("Of violet eyes, glistening as you weep")
print()
print("The wolf i will follow into the storm.")
print("To find your heart, it's passion displaced")
print("By ire ever growing, hardening into stone.")
print("Amidst the cold to hold you in a heated embrace")
print()
print("You flee my dream come the morning.")
print("Your scent - berries tart, lilac sweet")
print("To dream of raven locks entwisted, stormy.")
print("Of violet eyes, glistening as you weep")
print()
print("I know not if fate would have us live as one.")
print("Or if by love's blind chance we've been bound")
print("The wish i whispered, when it all began")
print("Did it forge a love you might have never have found?")
print()
print("You flee my dream come the morning.")
print("Your scent - berries tart, lilac sweet")
print("To dream of raven locks entwisted, stormy")
print("Of violet eyes, glistening as you weep.")
print()
print()

nome_musica=str("The Wolven Storm")
nome_guess=str(input("Qual o nome dessa música? "))
if nome_guess == nome_musica:
    print("Você acertou!")
else:
    print("masoq? não cara....")
